package com.github.goguma9071.jvmplus.processor;

import com.github.goguma9071.jvmplus.memory.Struct;
import com.google.auto.service.AutoService;
import com.squareup.javapoet.*;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.VarHandle;
import java.util.*;
import java.util.stream.Collectors;

/**
 * JVM Plus 미니 컴파일러 (Annotation Processor).
 * @Struct.Type 이 붙은 인터페이스를 분석하여 최적화된 구현체 클래스를 생성합니다.
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes("com.github.goguma9071.jvmplus.memory.Struct.Type")
@SupportedSourceVersion(SourceVersion.RELEASE_22)
public class StructProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(Struct.Type.class)) {
            if (element.getKind() != ElementKind.INTERFACE) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "@Struct.Type can only be applied to interfaces", element);
                continue;
            }

            try {
                generateImplementation((TypeElement) element);
            } catch (IOException e) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Failed to generate implementation: " + e.getMessage(), element);
            }
        }
        return true;
    }

    private void generateImplementation(TypeElement interfaceElement) throws IOException {
        String packageName = processingEnv.getElementUtils().getPackageOf(interfaceElement).getQualifiedName().toString();
        String interfaceName = interfaceElement.getSimpleName().toString();
        String implName = interfaceName + "Impl";

        // 1. 메소드 분석 및 레이아웃 계산 (C++ 스타일)
        List<ExecutableElement> methods = interfaceElement.getEnclosedElements().stream()
                .filter(e -> e.getKind() == ElementKind.METHOD)
                .map(e -> (ExecutableElement) e)
                .filter(m -> m.getAnnotation(Struct.Field.class) != null)
                .sorted(Comparator.comparingInt(m -> m.getAnnotation(Struct.Field.class).order()))
                .collect(Collectors.toList());

        // 구현체 클래스 빌더
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(implName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(TypeName.get(interfaceElement.asType()))
                .addField(MemorySegment.class, "segment", Modifier.PRIVATE, Modifier.FINAL)
                .addField(ClassName.get("com.github.goguma9071.jvmplus.memory", "MemoryPool"), "pool", Modifier.PRIVATE, Modifier.FINAL);

        // 생성자
        classBuilder.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(MemorySegment.class, "segment")
                .addParameter(ClassName.get("com.github.goguma9071.jvmplus.memory", "MemoryPool"), "pool")
                .addStatement("this.segment = segment")
                .addStatement("this.pool = pool")
                .build());

        // address() 메소드 구현
        classBuilder.addMethod(MethodSpec.methodBuilder("address")
                .addModifiers(Modifier.PUBLIC)
                .returns(long.class)
                .addStatement("return segment.address()")
                .build());

        // 필드별 Getter/Setter 구현
        for (ExecutableElement method : methods) {
            String name = method.getSimpleName().toString();
            boolean isSetter = method.getParameters().size() > 0;
            TypeMirror type = isSetter ? method.getParameters().get(0).asType() : method.getReturnType();
            
            // VarHandle을 통한 직접 접근 코드 생성 (리플렉션 없음!)
            // 실제 구현에서는 컴파일 타임에 오프셋을 상수로 미리 계산하여 박아넣어야 함.
            // 여기서는 단순화를 위해 MemoryManager의 런타임 레이아웃을 활용하지만, 
            // 최종적으로는 이 클래스 안에 오프셋 상수를 생성해야 함.
            
            if (isSetter) {
                classBuilder.addMethod(MethodSpec.methodBuilder(name)
                        .addModifiers(Modifier.PUBLIC)
                        .addParameter(TypeName.get(type), "v")
                        .addStatement("// Direct memory write (Code generated by Mini-Compiler)")
                        .addStatement("com.github.goguma9071.jvmplus.memory.MemoryManager.getHandle($T.class, $S).set(segment, 0L, v)", 
                                TypeName.get(interfaceElement.asType()), name)
                        .build());
            } else {
                classBuilder.addMethod(MethodSpec.methodBuilder(name)
                        .addModifiers(Modifier.PUBLIC)
                        .returns(TypeName.get(type))
                        .addStatement("return ($T) com.github.goguma9071.jvmplus.memory.MemoryManager.getHandle($T.class, $S).get(segment, 0L)", 
                                TypeName.get(type), TypeName.get(interfaceElement.asType()), name)
                        .build());
            }
        }

        // 파일 쓰기
        JavaFile.builder(packageName, classBuilder.build()).build().writeTo(processingEnv.getFiler());
    }
}
